In [ ]:
import requests
import pandas as pd

import os
from load_dotenv import load_dotenv

load_dotenv()
COINS = ["btc-bitcoin",
#  "eth-ethereum", "sol-solana", "xrp-xrp"
 ]

for coin_id in COINS:
    url = f"https://api.coinpaprika.com/v1/tickers/{coin_id}?quotes=USD"

    response = requests.get(url)

    if response.status_code == 200:
        data = response.json()
        # print(data)
        df = pd.DataFrame(data)
        df = pd.json_normalize(data)
    #     df = df.drop(columns=['rank', 'total_supply',
    #                  'max_supply', 'total_supply', 'max_supply' ,'beta_value', 'first_data_at', 'last_updated',  'quotes.USD.volume_24h_change_24h',
    #     'quotes.USD.market_cap_change_24h',
    #    'quotes.USD.percent_change_15m', 'quotes.USD.percent_change_30m',
    #    'quotes.USD.percent_change_1h', 'quotes.USD.percent_change_6h',
    #    'quotes.USD.percent_change_12h', 'quotes.USD.percent_change_24h',
    #    'quotes.USD.percent_change_7d', 'quotes.USD.percent_change_30d',
    #    'quotes.USD.percent_change_1y', 'quotes.USD.ath_price',
    #    'quotes.USD.ath_date', 'quotes.USD.percent_from_price_ath'])
        df = df[['id', 'name', 'symbol',
                 'quotes.USD.price', 'quotes.USD.volume_24h', 'quotes.USD.market_cap']]

        #     print(f"Exchange: {market['ex change_name']}, Price: {market['quotes']['USD']}")
        # print(response.text)
        print(f"Sucessfully Retrieved data  for coin {coin_id}")
    else:
        print(f"Failed to retrieve data")

Sucessfully Retrieved data  for coin btc-bitcoin

In [30]:
df.head()

,id,name,symbol,quotes.USD.price,quotes.USD.volume_24h,quotes.USD.market_cap
0,btc-bitcoin,Bitcoin,BTC,80235.762362,2.963657e+10,1606808116864

In [31]:
 df = df.rename(columns={'id': 'coint_id', 'name': 'coin_name', 'symbol': 'coin_symbol', 'quotes.USD.price': 'price_usd',
                       'quotes.USD.volume_24h': 'volume_24h_usd', 'quotes.USD.market_cap': 'market_cap_usd'})
df.head()

,coint_id,coin_name,coin_symbol,price_usd,volume_24h_usd,market_cap_usd
0,btc-bitcoin,Bitcoin,BTC,80235.762362,2.963657e+10,1606808116864